### ISSUE TITLE
PNGs fehlen

### ISSUE THREAD

**Issue by Obererpel** [ZusammenfassungenBaMaUniHro/Multiagentensysteme#1]
File img/regret.png not found
File img/formal language.png not found
File img/tell and ask.png not found

**Comment by aruscher** [comment]
eigentlich sind alle bilder drin o.0 im img ordner

**Comment by aruscher** [comment]
ggf nen Windows Problem wege Path-Separator? oder irg was von wegen leerzeichen?

**Comment by Obererpel** [comment]
Ich würde auch behaupten, Leerzeichen sind die Brut des Satanas. Ersetz mal durch _
